### PR TITLE
refactor(tas_status, too_old): rewrite tas status; use too_old everywhere

### PR DESCRIPTION
**Pull request by mtfurlan**
Untested, but more readable

### CODE REVIEW

**Comment by mtfurlan** [comment]
Any idea how we can make github say merged instead of closed next time?

**Comment by mkfink** [comment]
Not sure. I did:
```
$ git checkout fix/cleanup-tas_status
$ git rebase -i master
$ git checkout master
$ git merge fix/cleanup-tas_status
$ git push
$ git branch -D fix/cleanup-tas_status
$ git push origin :fix/cleanup-tas_status
```

**Comment by mtfurlan** [comment]
Ah, I think if you did
````
...
git rebase -i master
git push --force-with-lease
git checkout master
...
```
github would see it merged.

**Comment by mkfink** [comment]
Oh, yeah. That did it correctly on the other PR.

**Pull request closed without merging**
